/* Generated By:JavaCC: Do not edit this line. LugosiConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LugosiConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int ACHAVES = 6;
  /** RegularExpression Id. */
  int FCHAVES = 7;
  /** RegularExpression Id. */
  int VAR = 8;
  /** RegularExpression Id. */
  int SEMI = 9;
  /** RegularExpression Id. */
  int INT = 10;
  /** RegularExpression Id. */
  int BOOL = 11;
  /** RegularExpression Id. */
  int FLOAT = 12;
  /** RegularExpression Id. */
  int VOID = 13;
  /** RegularExpression Id. */
  int ATTRIB = 14;
  /** RegularExpression Id. */
  int APARENT = 15;
  /** RegularExpression Id. */
  int FPARENT = 16;
  /** RegularExpression Id. */
  int IF = 17;
  /** RegularExpression Id. */
  int WHILE = 18;
  /** RegularExpression Id. */
  int DO = 19;
  /** RegularExpression Id. */
  int RETURN = 20;
  /** RegularExpression Id. */
  int PRINT = 21;
  /** RegularExpression Id. */
  int TRUE = 22;
  /** RegularExpression Id. */
  int FALSE = 23;
  /** RegularExpression Id. */
  int OPSOMA = 24;
  /** RegularExpression Id. */
  int OPSUB = 25;
  /** RegularExpression Id. */
  int OPMULT = 26;
  /** RegularExpression Id. */
  int OPDIV = 27;
  /** RegularExpression Id. */
  int OPAND = 28;
  /** RegularExpression Id. */
  int OPOR = 29;
  /** RegularExpression Id. */
  int OPMENORQ = 30;
  /** RegularExpression Id. */
  int OPMAIORQ = 31;
  /** RegularExpression Id. */
  int OPIGUAL = 32;
  /** RegularExpression Id. */
  int OPCOMMA = 33;
  /** RegularExpression Id. */
  int FUNCTION = 34;
  /** RegularExpression Id. */
  int TOKEN_ID = 35;
  /** RegularExpression Id. */
  int TOKEN_NUMLITERAL = 36;
  /** RegularExpression Id. */
  int LETRA = 37;
  /** RegularExpression Id. */
  int DIGITO = 38;
  /** RegularExpression Id. */
  int DIGITOS = 39;
  /** RegularExpression Id. */
  int FACAO_OPCIONAL = 40;
  /** RegularExpression Id. */
  int EXPOENTE_OPCIONAL = 41;
  /** RegularExpression Id. */
  int LETRAOUDIGITO = 42;
  /** RegularExpression Id. */
  int FINALSUBLINHADO = 43;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"var\"",
    "\";\"",
    "\"int\"",
    "\"bool\"",
    "\"float\"",
    "\"void\"",
    "\":=\"",
    "\"(\"",
    "\")\"",
    "\"if\"",
    "\"while\"",
    "\"do\"",
    "\"return\"",
    "\"print\"",
    "\"true\"",
    "\"false\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\",\"",
    "\"function\"",
    "<TOKEN_ID>",
    "<TOKEN_NUMLITERAL>",
    "<LETRA>",
    "<DIGITO>",
    "<DIGITOS>",
    "<FACAO_OPCIONAL>",
    "<EXPOENTE_OPCIONAL>",
    "<LETRAOUDIGITO>",
    "<FINALSUBLINHADO>",
  };

}
